<div class="page-header">
    <div class="row">
        <div class="col-lg-12">
            <h1>Характеристики недвижимости</h1>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <a href="/param/add" class="btn btn-success btn-lg">Добавить</a>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <?php if (count($data)): ?>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Название</th>
                    <th scope="col">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($data as $key => $item): ?>
                    <tr<?= $key % 2 ? ' class="table-secondary"' : '' ?>>
                        <th scope="row"><?= $item['id'] ?></th>
                        <td><?= $item['name'] ?></td>
                        <td>
                            <a href="/param/edit/id/<?= $item['id'] ?>" class="btn btn-warning">Изменить</a>
                            <a href="/param/remove/id/<?= $item['id'] ?>" class="btn btn-danger">Удалить</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table> 
        <?php else: ?>
            Еще нет ни одной характеристики
        <?php endif; ?>
    </div>
</div>