<div class="page-header">
    <div class="row">
        <div class="col-lg-12">
            <h1>Объекты недвижимости</h1>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <a href="/realty/add" class="btn btn-success btn-lg">Добавить</a>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <?php if (count($data)): ?>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Создано</th>
                    <th scope="col">Тип</th>
                    <th scope="col">Адрес</th>
                    <th scope="col">Стоимость</th>
                    <th scope="col">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($data as $key => $item): ?>
                    <tr<?= $key % 2 ? ' class="table-secondary"' : '' ?>>
                        <th scope="row"><?= $item['id'] ?></th>
                        <td><?= Decorator::date($item['date_created']) ?></td>
                        <td><?= $item['type_name'] ?></td>
                        <td><?= $item['address'] ?></td>
                        <td><?= $item['price'] ?></td>
                        <td>
                            <a href="/realty/edit/id/<?= $item['id'] ?>" class="btn btn-warning">Изменить</a>
                            <a href="/realty/remove/id/<?= $item['id'] ?>" class="btn btn-danger">Удалить</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table> 
        <?php else: ?>
            Еще нет ни одного объекта
        <?php endif; ?>
    </div>
</div>